### PR TITLE
Bump nexus to 3.16.2-01, nexus-repository-helm to 0.0.9

### PR DESCRIPTION
**Pull request by patsevanton**
(brief, plain english overview of your changes here)

This pull request makes the following changes:
* (your change here)
* (another change here)
* (etc)

(If there are changes to the UI, please include a screenshot so we
know what to look for!)

(If there are changes to user behavior in general, please make sure to
update the docs, as well)

It relates to the following issue #s:
* Fixes #X

### CODE REVIEW

**Comment by patsevanton** [comment]
sign the Sonatype Contributor License Agreement.

**Comment by patsevanton** [comment]
@DarthHater Please check PR. Thanks!

**Comment by patsevanton** [comment]
@vsamotovka Please check PR. Thanks!

**Comment by patsevanton** [comment]
@loverto Please check PR. Thanks!

**Comment by patsevanton** [comment]
@g0blin79 Please check PR. Thanks!

**Comment by bhamail** [comment]
v0.0.9 is built against 3.16.2-01. 
see: https://github.com/sonatype-nexus-community/nexus-repository-helm/releases/tag/v.0.0.9

**Pull request closed without merging**
