### PR TITLE
Create initial index.yaml file for hosted repository

### LINKED ISSUE #23: Helm hosted repo does not create initial index.yaml file
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Add helm hosted repo locally when it's empty.
* **What feature or behavior is this required for?**
When adding empty helm hosted repo, it throw
`index.yaml file not exist` error.
Since there's no charts on the repo, there's no index.yaml file either.
* **How could we solve this issue? (Not knowing is okay!)**
The initial process for helm hosted repo should create an empty index.yaml and don't remove the file even the repo is empty.
* **Anything else?**
N/A

### PR DESCRIPTION
**Pull request by N4rm0**
This pull request makes the following changes:
* Generate index.yaml at hosted repository creation time 
* Generated index.yaml will have empty entries yaml object
* Update unit test

It relates to the following issue #s:
* Fixes #23

### CODE REVIEW

**Comment by N4rm0** [comment]
@DarthHater Could you please review this PR?

**Comment by MilosMosovsky** [comment]
👍 @N4rm0  Thank you for this, I tested it on my server and you saved me :) Works for me. Would be nice if someone will release this

**Comment by DarthHater** [comment]
I'll take a look at this ASAP. Thanks for pinging me!

**Comment by MilosMosovsky** [comment]
It actually closes #20, closes #23  and also closes #26 /cc @DarthHater

**Comment by bhamail** [comment]
verified index.yml is created when requested by add repos to helm client config. e.g.
```
helm repo add helm-proxy http://localhost:8081/repository/helm-proxy/
helm repo add helm-hosted http://localhost:8081/repository/helm-hosted/
```
both work fine (no 404 errors), and afterwards, an empty `index.yml` exists for both proxy and hosted repos.

Also verified using helm client to install a chart triggers a fetch of a fully populated 'index.yml' from the remote, and the helm client install succeeds.

Nicely done @N4rm0 ! Thanks for the contribution!

(Not sure if this fixes #20, as that one might be a 'sub-directory' issue)

Fixes #23, #26

**Pull request merged**
