### PR TITLE
Fixing compatibility issues

### PR DESCRIPTION
**Pull request by Darkvar**
Fixing compatibility issues with NXRM `3.19.0-SNAPSHOT`

### CODE REVIEW

**Comment by Darkvar** [comment]
CircleCI is failing because the latest NXRM `3.19.0-SNAPSHOT` with breakdown changes is not available on maven-central yet.

**Comment by chernikovmaksym** [comment]
@Darkvar maybe it's better to switch to 3.20-SNAPSHOT already?

**Comment by Darkvar** [comment]
> @Darkvar maybe it's better to switch to 3.20-SNAPSHOT already?

it's not required to fix the compatibility issue. Switching to the latest version is not required and we'll release `Helm` for `3.19.0` that's why we don't need `3.20.0-SNAPSHOT`

**Comment by Darkvar** [comment]
Closing this PR as not necessary anymore

**Pull request closed without merging**
