### PR TITLE
Added MAVEN_OPTS arg to the build container. This allows to pass opti…

### PR DESCRIPTION
**Pull request by BabisK**
Added MAVEN_OPTS arg to the build container. This allows to pass options to maven, useful for proxies etc.

`docker build --build-arg MAVEN_OPTS="-Dhttp.proxyHost=proxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy -Dhttps.proxyPort=3128" .`

This pull request makes the following changes:
* Adds MAVEN_OPTS argument to the build container

### CODE REVIEW

**Comment by BabisK** [comment]
I signed the CLA but the tag isn't being removed.

**Comment by davidkarlsen** [comment]
@sonabot help

**Comment by davidkarlsen** [comment]
@sonatypecla help

**Comment by davidkarlsen** [comment]
@bhamail can this be merged?

**Comment by BabisK** [comment]
Since this is in base Nexus now, the patch is irrelevant.

**Pull request closed without merging**
